# Dockerfile.bot
FROM python:3.10-slim

RUN apt update -y && \
    apt install -y gcc libssl-dev libffi-dev curl bash && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copy only setup + source first
COPY setup.py ./
COPY . .

# Install your package (and its deps from install_requires)
RUN pip install --upgrade pip && pip install .

RUN chmod +x Credentials.sh

CMD ["bash", "-lc", "source ./Credentials.sh && python -u main.py --server"]
